workflows:
  ios-release:
    name: iOS Release Build (Darklick)

    environment:
      node: 18
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.darklick.app
      groups:
        - appstore-connect
      vars:
        XCODE_SCHEME: "Darklick"
        XCODE_WORKSPACE: "ios/Darklick.xcworkspace"
        BUNDLE_ID: "com.darklick.app"
        TEAM_ID: "5YYR6ZRQTZ"

    scripts:
      - name: Install deps
        script: npm install

      - name: Generate iOS
        script: npx expo prebuild --platform ios --clean

      - name: Install pods
        script: cd ios && pod install && cd ..

      - name: Build IPA
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/Darklick.xcarchive \
            -allowProvisioningUpdates \
            -allowProvisioningDeviceRegistration \
            DEVELOPMENT_TEAM=$TEAM_ID \
            CODE_SIGN_STYLE=Automatic \
            PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID \
            archive

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/Darklick.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build \
            -allowProvisioningUpdates

    artifacts:
      - build/**/*.ipa

    publishing:
      app_store_connect:
        api_key: 48MDJK7UF8
        key_id: 48099666-494d-47dc-a15c-f9ecc09cfc21
        issuer_id: MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgqZnpGpGsabjJVIAIkF8/ceJokBr2u8csWU6GhUuBWCagCgYIKoZIzj0DAQehRANCAATc8sSBAh2SUyGJDofyrNNksUG8a5S2lYtM/WeQyf7MKiqKBnREHpA7EZT585XN6rj7jq2QtKAIFmePHpMjwf5K
        submit_to_testflight: true
